#include "stdio.h"
#include "stdlib.h"
#include "colorPrint.h"

int main() {
	/**
	 *	Printing test for FORMAT parameter
	*/
	printColor(FORMAT_DEFAULT, NULL_PARAM, NULL_PARAM, "FORMAT_DEFAULT\n");
	printColor(FORMAT_BOLD, NULL_PARAM, NULL_PARAM, "FORMAT_BOLD\n");
	printColor(FORMAT_DIM, NULL_PARAM, NULL_PARAM, "FORMAT_DIM\n");
	printColor(FORMAT_ITALIC, NULL_PARAM, NULL_PARAM, "FORMAT_ITALIC\n");
	printColor(FORMAT_UNDERLINE, NULL_PARAM, NULL_PARAM, "FORMAT_UNDERLINE\n");
	printColor(FORMAT_BLINK, NULL_PARAM, NULL_PARAM, "FORMAT_BLINK\n");
	printColor(FORMAT_SURLINE, NULL_PARAM, NULL_PARAM, "FORMAT_SURLINE\n");
	printColor(FORMAT_HIDDEN, NULL_PARAM, NULL_PARAM, "FORMAT_HIDDEN\n");
	printColor(FORMAT_CROSS, NULL_PARAM, NULL_PARAM, "FORMAT_CROSS\n");
	printColor(FORMAT_DUNDERLINE, NULL_PARAM, NULL_PARAM, "FORMAT_DUNDERLINE\n");

	/**
	 *	Printing test for BACK_COLOR parameter
	*/
	printColor(BACK_COLOR_BLACK, NULL_PARAM, NULL_PARAM, "BACK_COLOR_BLACK\n");
	printColor(BACK_COLOR_RED, NULL_PARAM, NULL_PARAM, "BACK_COLOR_RED\n");
	printColor(BACK_COLOR_GREEN, NULL_PARAM, NULL_PARAM, "BACK_COLOR_GREEN\n");
	printColor(BACK_COLOR_YELLOW, NULL_PARAM, NULL_PARAM, "BACK_COLOR_YELLOW\n");
	printColor(BACK_COLOR_BLUE, NULL_PARAM, NULL_PARAM, "BACK_COLOR_BLUE\n");
	printColor(BACK_COLOR_PURPLE, NULL_PARAM, NULL_PARAM, "BACK_COLOR_PURPLE\n");
	printColor(BACK_COLOR_CYAN, NULL_PARAM, NULL_PARAM, "BACK_COLOR_CYAN\n");
	printColor(BACK_COLOR_WHITE, NULL_PARAM, NULL_PARAM, "BACK_COLOR_WHITE\n");

	/**
	 *	Printing test for TEXT_COLOR parameter
	*/
	printColor(TEXT_COLOR_BLACK, NULL_PARAM, NULL_PARAM, "TEXT_COLOR_BLACK\n");
	printColor(TEXT_COLOR_RED, NULL_PARAM, NULL_PARAM, "TEXT_COLOR_RED\n");
	printColor(TEXT_COLOR_GREEN, NULL_PARAM, NULL_PARAM, "TEXT_COLOR_GREEN\n");
	printColor(TEXT_COLOR_YELLOW, NULL_PARAM, NULL_PARAM, "TEXT_COLOR_YELLOW\n");
	printColor(TEXT_COLOR_BLUE, NULL_PARAM, NULL_PARAM, "TEXT_COLOR_BLUE\n");
	printColor(TEXT_COLOR_PURPLE, NULL_PARAM, NULL_PARAM, "TEXT_COLOR_PURPLE\n");
	printColor(TEXT_COLOR_CYAN, NULL_PARAM, NULL_PARAM, "TEXT_COLOR_CYAN\n");
	printColor(TEXT_COLOR_WHITE, NULL_PARAM, NULL_PARAM, "TEXT_COLOR_WHITE\n");

	/**
	 *	Printing test for multiple configurations
	*/
	printColor(FORMAT_UNDERLINE, BACK_COLOR_PURPLE, TEXT_COLOR_YELLOW, "FORMAT_UNDERLINE BACK_COLOR_PURPLE TEXT_COLOR_YELLOW\n");
	printColor(NULL_PARAM, FORMAT_CROSS, TEXT_COLOR_GREEN, "NULL_PARAM FORMAT_CROSS TEXT_COLOR_GREEN\n");
	printColor(BACK_COLOR_RED, NULL_PARAM, FORMAT_BLINK, "BACK_COLOR_RED NULL_PARAM FORMAT_BLINK\n");
	printColor(NULL_PARAM, NULL_PARAM, BACK_COLOR_CYAN, "NULL_PARAM NULL_PARAM BACK_COLOR_CYAN\n");
	printColor(TEXT_COLOR_RED, BACK_COLOR_YELLOW, NULL_PARAM, "TEXT_COLOR_RED BACK_COLOR_YELLOW NULL_PARAM\n");
	printColor(NULL_PARAM, FORMAT_ITALIC, NULL_PARAM, "NULL_PARAM FORMAT_ITALIC NULL_PARAM\n");
	printColor(TEXT_COLOR_WHITE, NULL_PARAM, NULL_PARAM, "TEXT_COLOR_WHITE NULL_PARAM NULL_PARAM\n");
	printColor(NULL_PARAM, NULL_PARAM, NULL_PARAM, "NULL_PARAM NULL_PARAM NULL_PARAM\n");

	/**
	 *	Printing test for printColorNoR
	*/
	printColorNoR(FORMAT_BOLD, BACK_COLOR_WHITE, TEXT_COLOR_GREEN, "Test for printColorNoR\n");
	printf("Just a normal printf\n");
	printf("Another normal printf\n");
	resetColor();
	printf("Printf after resetColor\n");
	exit(0);
}